/*
    liblifx - lifx_products.h
    Definitions for all LIFX products and their capabilities.
*/

#ifndef LIFX_PRODUCTS_H_
#define LIFX_PRODUCTS_H_

#include <stdint.h>
#include <stdbool.h>

typedef struct _lifx_product_info_t
{
    int id;
    char *product_name;
    uint16_t temp_min;
    uint16_t temp_max;
    bool hev;
    bool color;
    bool chain;
    bool matrix;
    bool relays;
    bool buttons;
    bool infrared;
    bool multizone;
    bool extended_multizone;
} lifx_product_info_t;

const static lifx_product_info_t lifx_products[] = 
{
    {
        .id = 1,
        .product_name = "LIFX Original 1000",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 3,
        .product_name = "LIFX Color 650",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 10,
        .product_name = "LIFX White 800 (Low Voltage)",
        .temp_min = 2700,
        .temp_max = 6500,
    },
    {
        .id = 11,
        .product_name = "LIFX White 800 (High Voltage)",
        .temp_min = 2700,
        .temp_max = 6500,
    },
    {
        .id = 15,
        .product_name = "LIFX Color 1000",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 18,
        .product_name = "LIFX White 900 BR30 (Low Voltage)",
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 19,
        .product_name = "LIFX White 900 BR30 (High Voltage)",
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 20,
        .product_name = "LIFX Color 1000 BR30",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 22,
        .product_name = "LIFX Color 1000",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 27,
        .product_name = "LIFX A19",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 28,
        .product_name = "LIFX BR30",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 29,
        .product_name = "LIFX A19 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 30,
        .product_name = "LIFX BR30 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 31,
        .product_name = "LIFX Z",
        .color = true,
        .multizone = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 32,
        .product_name = "LIFX Z",
        .color = true,
        .multizone = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 36,
        .product_name = "LIFX Downlight",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 37,
        .product_name = "LIFX Downlight",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 38,
        .product_name = "LIFX Beam",
        .color = true,
        .multizone = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 39,
        .product_name = "LIFX Downlight White to Warm",
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 40,
        .product_name = "LIFX Downlight",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 43,
        .product_name = "LIFX A19",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 44,
        .product_name = "LIFX BR30",
        .color = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 45,
        .product_name = "LIFX A19 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 46,
        .product_name = "LIFX BR30 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 49,
        .product_name = "LIFX Mini Color",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 50,
        .product_name = "LIFX Mini White to Warm",
        .temp_min = 1500,
        .temp_max = 6500,
    },
    {
        .id = 51,
        .product_name = "LIFX Mini White",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 52,
        .product_name = "LIFX GU10",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 53,
        .product_name = "LIFX GU10",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 55,
        .product_name = "LIFX Tile",
        .color = true,
        .chain = true,
        .matrix = true,
        .temp_min = 2500,
        .temp_max = 9000,
    },
    {
        .id = 57,
        .product_name = "LIFX Candle",
        .color = true,
        .matrix = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 59,
        .product_name = "LIFX Mini Color",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 60,
        .product_name = "LIFX Mini White to Warm",
        .temp_min = 1500,
        .temp_max = 6500,
    },
    {
        .id = 61,
        .product_name = "LIFX Mini White",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 62,
        .product_name = "LIFX A19",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 63,
        .product_name = "LIFX BR30",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 64,
        .product_name = "LIFX A19 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 65,
        .product_name = "LIFX BR30 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 66,
        .product_name = "LIFX Mini White",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 68,
        .product_name = "LIFX Candle",
        .color = true,
        .matrix = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 70,
        .product_name = "LIFX Switch",
        .relays = true,
        .buttons = true,
    },
    {
        .id = 71,
        .product_name = "LIFX Switch",
        .relays = true,
        .buttons = true,
    },
    {
        .id = 81,
        .product_name = "LIFX Candle White to Warm",
        .temp_min = 2200,
        .temp_max = 6500,
    },
    {
        .id = 82,
        .product_name = "LIFX Filament Clear",
        .temp_min = 2100,
        .temp_max = 2100,
    },
    {
        .id = 85,
        .product_name = "LIFX Filament Amber",
        .temp_min = 2000,
        .temp_max = 2000,
    },
    {
        .id = 87,
        .product_name = "LIFX Mini White",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 88,
        .product_name = "LIFX Mini White",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 89,
        .product_name = "LIFX Switch",
        .relays = true,
        .buttons = true,
    },
    {
        .id = 90,
        .product_name = "LIFX Clean",
        .hev = true,
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 91,
        .product_name = "LIFX Color",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 92,
        .product_name = "LIFX Color",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 93,
        .product_name = "LIFX A19 US",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 94,
        .product_name = "LIFX BR30",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 96,
        .product_name = "LIFX Candle White to Warm",
        .temp_min = 2200,
        .temp_max = 6500,
    },
    {
        .id = 97,
        .product_name = "LIFX A19",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 98,
        .product_name = "LIFX BR30",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 99,
        .product_name = "LIFX Clean",
        .hev = true,
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 100,
        .product_name = "LIFX Filament Clear",
        .temp_min = 2100,
        .temp_max = 2100,
    },
    {
        .id = 101,
        .product_name = "LIFX Filament Amber",
        .temp_min = 2000,
        .temp_max = 2000,
    },
    {
        .id = 109,
        .product_name = "LIFX A19 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 110,
        .product_name = "LIFX BR30 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 111,
        .product_name = "LIFX A19 Night Vision",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 112,
        .product_name = "LIFX BR30 Night Vision Intl",
        .color = true,
        .infrared = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 113,
        .product_name = "LIFX Mini WW US",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 114,
        .product_name = "LIFX Mini WW Intl",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 115,
        .product_name = "LIFX Switch",
        .relays = true,
        .buttons = true,
    },
    {
        .id = 116,
        .product_name = "LIFX Switch",
        .relays = true,
        .buttons = true,
    },
    {
        .id = 117,
        .product_name = "LIFX Z US",
        .color = true,
        .multizone = true,
        .extended_multizone = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 118,
        .product_name = "LIFX Z Intl",
        .color = true,
        .multizone = true,
        .extended_multizone = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 119,
        .product_name = "LIFX Beam US",
        .color = true,
        .multizone = true,
        .extended_multizone = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 120,
        .product_name = "LIFX Beam Intl",
        .color = true,
        .multizone = true,
        .extended_multizone = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 123,
        .product_name = "LIFX Color US",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 124,
        .product_name = "LIFX Color Intl",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 125,
        .product_name = "LIFX White to Warm US",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 126,
        .product_name = "LIFX White to Warm Intl",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 127,
        .product_name = "LIFX White US",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 128,
        .product_name = "LIFX White Intl",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 129,
        .product_name = "LIFX Color US",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 130,
        .product_name = "LIFX Color Intl",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 131,
        .product_name = "LIFX White To Warm US",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 132,
        .product_name = "LIFX White To Warm Intl",
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 133,
        .product_name = "LIFX White US",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 134,
        .product_name = "LIFX White Intl",
        .temp_min = 2700,
        .temp_max = 2700,
    },
    {
        .id = 135,
        .product_name = "LIFX GU10 Color US",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 136,
        .product_name = "LIFX GU10 Color Intl",
        .color = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 137,
        .product_name = "LIFX Candle Color US",
        .color = true,
        .matrix = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
    {
        .id = 138,
        .product_name = "LIFX Candle Color Intl",
        .color = true,
        .matrix = true,
        .temp_min = 1500,
        .temp_max = 9000,
    },
};
const static int lifx_products_count = sizeof(lifx_products) / sizeof(lifx_products[0]);

#endif // LIFX_PRODUCTS_H_
